export const businessCardTemplates = [
  {
    id: "classic-navy",
    name: "Classic Navy",
    layout: "left-panel",
    panelBg: "#0f172a",
    panelText: "#f8fafc",
    accent: "#c9a94a",
    bodyBg: "#ffffff",
    bodyText: "#1e293b",
    font: "serif",
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    layout: "minimal-border",
    borderColor: "#111827",
    bodyBg: "#ffffff",
    bodyText: "#111827",
    accent: "#111827",
    font: "sans",
  },
  {
    id: "modern-gradient",
    name: "Modern Gradient",
    layout: "top-band",
    bandGradient: "linear-gradient(120deg, #7c3aed, #db2777)",
    bandText: "#ffffff",
    bodyBg: "#ffffff",
    bodyText: "#1f2937",
    accent: "#db2777",
    font: "sans",
  },
  {
    id: "bold-split",
    name: "Bold Split",
    layout: "diagonal-split",
    blockBg: "#0f172a",
    blockText: "#ffffff",
    bodyBg: "#ffffff",
    bodyText: "#0f172a",
    accent: "#0f172a",
    font: "sans",
  },
  {
    id: "tech-mono",
    name: "Tech Mono",
    layout: "left-panel",
    panelBg: "#020617",
    panelText: "#67e8f9",
    accent: "#22d3ee",
    bodyBg: "#0f172a",
    bodyText: "#e2e8f0",
    font: "mono",
  },
  {
    id: "elegant-gold",
    name: "Elegant Gold",
    layout: "centered",
    bodyBg: "#111111",
    bodyText: "#f5e7c1",
    accent: "#d4af37",
    font: "serif",
  },
  {
    id: "creative-circles",
    name: "Creative Circles",
    layout: "circles",
    bodyBg: "#fff7f5",
    bodyText: "#7c2d12",
    accent: "#fb7185",
    circleColor: "#fdba74",
    font: "sans",
  },
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    layout: "top-band",
    bandGradient: "#1d4ed8",
    bandText: "#ffffff",
    bodyBg: "#ffffff",
    bodyText: "#1e293b",
    accent: "#1d4ed8",
    font: "sans",
  },
  {
    id: "nature-green",
    name: "Nature Green",
    layout: "left-panel",
    panelBg: "linear-gradient(160deg, #14532d, #15803d)",
    panelText: "#f0fdf4",
    accent: "#86efac",
    bodyBg: "#ffffff",
    bodyText: "#14532d",
    font: "sans",
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    layout: "diagonal-split",
    blockBg: "linear-gradient(135deg, #f97316, #dc2626)",
    blockText: "#ffffff",
    bodyBg: "#fff7ed",
    bodyText: "#7c2d12",
    accent: "#ea580c",
    font: "sans",
  },
];
