import {
  FileImage,
  FileText,
  Layers,
  ImageDown,
  RefreshCcw,
  Sparkles,
  QrCode,
  Type,
  Hash,
  Crop,
  Receipt,
  FileUser,
  Braces,
  Hash as HashIcon,
  SquarePlay,
  BadgePercent,
  ReceiptIndianRupee,
  IdCard,
  Cake,
  MoonStar,
  Globe,
  Keyboard,
  CaseSensitive,
} from "lucide-react";

export const tools = [
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Combine one or more images into a single PDF file.",
    icon: FileText,
    path: "/tools/jpg-to-pdf",
    color: "from-rose-500 to-orange-400",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Turn every page of a PDF into a downloadable JPG image.",
    icon: FileImage,
    path: "/tools/pdf-to-jpg",
    color: "from-sky-500 to-cyan-400",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
  },
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one, in the order you choose.",
    icon: Layers,
    path: "/tools/merge-pdf",
    color: "from-violet-500 to-purple-400",
    category: "PDF Tools",
    categorySlug: "pdf-tools",
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Shrink image file size while keeping good quality.",
    icon: ImageDown,
    path: "/tools/image-compressor",
    color: "from-emerald-500 to-teal-400",
    category: "Image Tools",
    categorySlug: "image-tools",
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG",
    description: "Convert Apple HEIC photos into universally supported JPG.",
    icon: RefreshCcw,
    path: "/tools/heic-to-jpg",
    color: "from-amber-500 to-yellow-400",
    category: "Image Tools",
    categorySlug: "image-tools",
  },
  {
    id: "ai-prompt-generator",
    name: "AI Image Prompt Generator",
    description: "Upload an image and get AI image-generation prompts describing it.",
    icon: Sparkles,
    path: "/tools/ai-prompt-generator",
    color: "from-fuchsia-500 to-pink-400",
    category: "AI Tools",
    categorySlug: "ai-tools",
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Crop images to the exact size you need, right in your browser.",
    icon: Crop,
    path: "/tools/image-cropper",
    color: "from-teal-500 to-cyan-400",
    category: "Image Tools",
    categorySlug: "image-tools",
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, and sentences as you type.",
    icon: Hash,
    path: "/tools/word-counter",
    color: "from-blue-500 to-indigo-400",
    category: "Text Tools",
    categorySlug: "text-tools",
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder titles, paragraphs, or lists in seconds.",
    icon: Type,
    path: "/tools/lorem-ipsum-generator",
    color: "from-purple-500 to-violet-400",
    category: "Text Tools",
    categorySlug: "text-tools",
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Turn any text or link into a scannable QR code instantly.",
    icon: QrCode,
    path: "/tools/qr-code-generator",
    color: "from-slate-700 to-slate-500",
    category: "Utilities",
    categorySlug: "utilities",
  },
  {
    id: "invoice-generator",
    name: "Invoice Generator",
    description: "Create a professional invoice with line items and totals, then download it as a PDF.",
    icon: Receipt,
    path: "/tools/invoice-generator",
    color: "from-green-600 to-emerald-500",
    category: "Business Tools",
    categorySlug: "business-tools",
  },
  {
    id: "salary-slip-generator",
    name: "Salary Slip Generator",
    description: "Create a detailed payslip with earnings, deductions, and auto-calculated PF/ESI, then download it as a PDF.",
    icon: ReceiptIndianRupee,
    path: "/tools/salary-slip-generator",
    color: "from-teal-600 to-emerald-500",
    category: "Business Tools",
    categorySlug: "business-tools",
  },
  {
    id: "resume-builder",
    name: "Resume Builder",
    description: "Build a creative resume with a photo, work history, and skills, then download it as a PDF.",
    icon: FileUser,
    path: "/tools/resume-builder",
    color: "from-blue-600 to-cyan-500",
    category: "Career Tools",
    categorySlug: "career-tools",
  },
  {
    id: "business-card-maker",
    name: "Business Card Maker",
    description: "Pick a template and design a professional business card with your details, then download it.",
    icon: IdCard,
    path: "/tools/business-card-maker",
    color: "from-violet-600 to-fuchsia-500",
    category: "Design Tools",
    categorySlug: "design-tools",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, and minify JSON with instant error feedback.",
    icon: Braces,
    path: "/tools/json-formatter",
    color: "from-amber-600 to-orange-500",
    category: "Utilities",
    categorySlug: "utilities",
  },
  {
    id: "hashtag-generator",
    name: "Hashtag Generator",
    description: "Generate trending, category-specific hashtags for your posts.",
    icon: HashIcon,
    path: "/tools/hashtag-generator",
    color: "from-pink-500 to-rose-400",
    category: "Utilities",
    categorySlug: "utilities",
  },
  {
    id: "youtube-money-calculator",
    name: "YouTube Money Calculator",
    description: "Look up any YouTube channel's stats and estimate its ad revenue.",
    icon: SquarePlay,
    path: "/tools/youtube-money-calculator",
    color: "from-red-600 to-rose-500",
    category: "Creator Tools",
    categorySlug: "creator-tools",
  },
  {
    id: "gst-calculator",
    name: "GST Calculator",
    description: "Calculate GST amount and total from an amount, instantly and for free.",
    icon: BadgePercent,
    path: "/tools/gst-calculator",
    color: "from-green-600 to-emerald-500",
    category: "Business Tools",
    categorySlug: "business-tools",
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    description: "Your exact age, planetary ages, life stats, milestones, and Indian govt job eligibility.",
    icon: Cake,
    path: "/tools/age-calculator",
    color: "from-amber-500 to-orange-400",
    category: "Utilities",
    categorySlug: "utilities",
  },
  {
    id: "kundli",
    name: "Free Online Kundli",
    description: "Generate a Vedic birth chart with planet positions, dosha, dasha, and remedies.",
    icon: MoonStar,
    path: "/tools/kundli",
    color: "from-amber-500 to-yellow-400",
    category: "Astrology",
    categorySlug: "astrology",
  },
  {
    id: "domain-name-search",
    name: "Domain Name Search",
    description: "Search a keyword across 40+ domain extensions and see which ones are available.",
    icon: Globe,
    path: "/tools/domain-name-search",
    color: "from-cyan-600 to-blue-500",
    category: "Utilities",
    categorySlug: "utilities",
  },
  {
    id: "english-to-hindi-typing",
    name: "English to Hindi Typing",
    description: "Type in English (Roman letters) and get accurate Hindi (Devanagari) text instantly.",
    icon: Keyboard,
    path: "/tools/english-to-hindi-typing",
    color: "from-orange-500 to-rose-400",
    category: "Text Tools",
    categorySlug: "text-tools",
  },
  {
    id: "convert-case",
    name: "Convert Case",
    description: "Switch text between sentence case, UPPER CASE, Title Case, and more in one click.",
    icon: CaseSensitive,
    path: "/tools/convert-case",
    color: "from-violet-500 to-indigo-400",
    category: "Text Tools",
    categorySlug: "text-tools",
  },
];
